version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./volume:/app
    depends_on:
      - voicevox
    restart: always

  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    restart: always
    volumes:
      - voicevox-local-config:/opt/voicevox_engine
    ports:
      - 50022
    environment:
      - ACCESS_CONTROL_ALLOW_ORIGIN=*

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "81:80"
    depends_on:
      - web
    restart: always

volumes:
  voicevox-local-config:
