version: '3'
services:
  web:
    image: flask-image
    build: ./flask-app
    ports:
      - "5000:5000"
    depends_on:
      - voicevox_engine
  voicevox_engine:
    image: hiroshiba/voicevox_engine
    expose:
      - "50021"
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
